services:
  server:
    image: server:1.0.0
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    networks:
      main:
        ipv4_address: 172.23.0.5
    ports: 
      - 8000:8000
    volumes:
      - ./server:/server
      - server-v-node-modules:/server/node_modules
    depends_on:
      database:
        condition: service_healthy

  database:
    image: database:1.0.0
    container_name: ${DB_HOST}
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - 5432:5432     
    volumes:
    - database-v:/var/lib/posgresql/data
    command: "-p ${DB_PORT}"
    networks:
      main:
        ipv4_address: 172.23.0.6
    healthcheck:
      test: ["CMD-SHELL","pg_isready -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      start_period: 0s
      retries: 5

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"

networks:
  main:
    name: my_first_net
    external: true


